image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: |
      bash .gp/bash/before-tasks.sh
      nvm install node npm
      npm install -g jshint
      npm ci --cache .npm --prefer-offline
    init: |
      docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_TOKEN"
      docker pull strausmann/minecraft-bedrock-connect:latest

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 19132
    onOpen: ignore
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - GitLab.gitlab-workflow
    - josee9988.changelog-and-markdown-snippets
